### ISSUE TITLE
Make the Portfolio Less overwhelming

### ISSUE THREAD

**Issue by hennessyevan** [VekLabs/veklabs.com#82]
```[tasklist]
### Tasks
- [x] ~Six videos on the homepage
- [x] "View All" to portfolio page
- [x] Page with filters for categories, etc.
- [x] Portfolio Link in header
- [x] Portfolio title to separate the "who" of veklabs and the work
- [x] Polish (mobile, animations)
```
